<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CPC-rdevunur-RN" failures="0" tests="1" name="TestExecute.OXO.unitTestcase.Test_DGLD_OXO_UT_Address_Book_052_Alternate_Path_User_Changes_Default_ShippingAddress" time="4.428" errors="1" timestamp="7 Sep 2022 11:39:50 GMT">
  <testcase classname="TestExecute.OXO.unitTestcase.Test_DGLD_OXO_UT_Address_Book_052_Alternate_Path_User_Changes_Default_ShippingAddress" name="Alternate_Path_User_Changes_Default_ShippingAddress" time="4.428">
    <error message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at TestComponent.OXO.OxoHelper.verifingHomePage(OxoHelper.java:74)
	at TestExecute.OXO.unitTestcase.Test_DGLD_OXO_UT_Address_Book_052_Alternate_Path_User_Changes_Default_ShippingAddress.Alternate_Path_User_Changes_Default_ShippingAddress(Test_DGLD_OXO_UT_Address_Book_052_Alternate_Path_User_Changes_Default_ShippingAddress.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Alternate_Path_User_Changes_Default_ShippingAddress -->
</testsuite> <!-- TestExecute.OXO.unitTestcase.Test_DGLD_OXO_UT_Address_Book_052_Alternate_Path_User_Changes_Default_ShippingAddress -->
